export const projects = [
  {
    title: 'Personal Portfolio',
    description: "My personal portfolio, where you are navigating just now :). It's all responsive and realized with React and Nextjs",
    image: '/images/portfolio.png',
    tags: ['React', 'Nextjs'],
    source: 'https://github.com/luigiPinna/Personal-portfolio',
    visit: 'https://luigipinna.com',
    id: 0,
  },
  {
    title: 'Tetris - Javascript',
    description: "I reproduced the base of Tetris game. I created it just to improve my Javascript skills.",
    image: '/images/tetris.png',
    tags: ['Vanilla Javascript'],
    source: 'https://github.com/luigiPinna/Tetris_javascript/tree/main/public',
    visit: '',
    id: 1,
  },
  {
    title: 'The NetFish',
    description: "Made by using Angular, SpringBoot, Dotnet, Laravel, and SpringBoot Security technologies. This web application allows users to choose interesting films based on wheater conditions and time. People can search for their preferred movie or fiction. Each user has a personal account where can put movies in a list of movies seen or must-see in the future.",
    image: '/images/thenetfish.png',
    tags: ['MySQL', 'SpringBoot', 'Dotnet', 'Angular'],
    source: 'https://github.com/luigiPinna/TheNetFish-project-revisited',
    visit: '',
    id: 2,
  },
  {
    title: 'Agenda Contacts app',
    description: "This is a Contacts and Agenda application. Contacts are saved in the Database using Java backend and the interface is made in Angular. This app also allows you to write some notes of the day that you can view in a note dashboard or delete and update them.",
    image: '/images/contacts.png',
    tags: ['MySQL', 'Spring', 'Angular'],
    source: 'https://github.com/luigiPinna/Contacts-with-Spring-Backend-and-Angular-Frontend',
    visit: '',
    id: 3,
  },
  {
    title: 'API Economics Articles Scraper',
    description: "I created this API because I needed only business articles from the majority of online newspapers. This app returns you a JSON where there are most of business and finance articles from the web",
    image: '/images/apinews.png',
    tags: ['React', 'Express', 'Axios', 'Cheerio'],
    source: '',
    visit: '',
    id: 4,
  },
  {
    title: 'Cryptocurrency Converter',
    description:"Cryptocurrencies Converter allows you to convert the most popular crypto values in others or in your preferred Fiat currency. This app is optimized for mobile use, it's realized, on the backend side, by using some crypto APIs called with Node and services like Express and Axios. The UI is created in React and javascript.",
    image: '/images/crypto.png',
    tags: ['React', 'API', 'Express', 'Axios', 'Node'],
    source: 'https://github.com/luigiPinna/Cryptocurrency-Converter',
    visit: 'https://cryptocurrenciesconverter.web.app/',
    id: 5,
  },
  {
    title: 'OpenAI Image Generator',
    description: "Made by using OpenAI APIs, developed with Javascript. This simple interface allows users to generate an image created by artificial intelligence based on a description entered by the user.",
    image: '/images/AiDog.png',
    tags: ['Javascript', 'OpenAI', 'API', 'Bootstrap'],
    source: 'https://github.com/luigiPinna/openai-generate-image',
    visit: '',
    id: 6,
  },
  {
    title: 'DocuMentor',
    description: "DocuMentor is an ai tool when users can ask natural language questions and receive accurate, context-aware answers extracted directly from PDF documents.",
    image: '/images/docuMentor.png',
    tags: ['Python', 'OpenAI', 'llamaindex', 'LLM', 'Ai'],
    source: 'https://github.com/luigiPinna/DocuMentor',
    visit: '',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey' },
  { year: 2019, text: 'Earned my Bachelor’s Degree in Business and Economics' },
  { year: 2020, text: 'Worked in IT and Marketing' },
  { year: 2021, text: 'Finished Full Stack Developer Academy at TheNetValue' },
  { year: 2021, text: 'Joined a startup as a Backend Developer' },
  { year: 2024, text: 'Became a Full Stack Developer' },
];

